config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :seating_plans, only: [:create, :show, :update ] do
    resources :tables, only: [:index, :update]
    resources :participants, only: [:create] do
      patch 'swap'
      put 'swap'
    end
    resources :relationships, only: [:create]
    get 'export'
    get 'deco'
 end

  resources :participants, only: [:update, :destroy], shallow: true

  get 'tables/find_for_modal', as: "find_for_modal"



end

app/models/seating_plan.rb
require 'csv'

class SeatingPlan < ApplicationRecord
  belongs_to :user
  has_many :tables
  has_many :participants
  has_many :relationships, through: :participants
  validates :nb_participants, presence: true
  validates :nb_max_participants, presence: true
  validates :nb_tables, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  def default_name
    "My Seating Plan" if name.nil?
  end

  def to_csv(options = {})
    desired_columns = ["name", "age_range", "family_type", "seat"]
    CSV.generate(options) do |csv|
      csv << desired_columns
      @seating_plan.participants.each do |participant|
      csv << participant.attributes.values_at(desired_columns)
      end
    end
  end


  def define_table_nb
    if nb_participants.to_i + nb_max_participants.to_i != 0
      self.nb_tables = (self.nb_participants / self.nb_max_participants)
      self.nb_tables += 1 if (nb_participants % nb_max_participants) != 0
    end
  end


end

app/controllers/seating_plans_controller.rb
class SeatingPlansController < ApplicationController
  before_action :init, only: [:export, :deco]

  def create
    @seating_plan = current_user.seating_plans.new(seating_plan_params)
    @seating_plan.default_name

    @seating_plan.define_table_nb
    if @seating_plan.save
      @bride = Participant.create(
        first_name: current_user.bride_first_name,
        last_name: current_user.bride_last_name,
        seating_plan: @seating_plan,
        seat: 1,
        age_range: 2,
        family_type: 1,
        status: 1
        )
      @groom = Participant.create(
        first_name: current_user.groom_first_name,
        last_name: current_user.groom_last_name,
        seating_plan: @seating_plan,
        seat: 2,
        age_range: 2,
        family_type: 0,
        status: 0
        )

      r = Relationship.create(link: "couple", first_guest: @bride, second_guest: @groom)
      r.reverse_relationship

      @seating_plan.nb_tables.times do |n|

        @seating_plan.tables.create(name: "Table #{n + 1}", nb_max_participants: @seating_plan.nb_max_participants)
      end
      redirect_to seating_plan_tables_path(@seating_plan)
    else
      flash[:alert] = "Please review your inputs"
      redirect_to root_path
    end
  end

  def show
    #@seating_plan = SeatingPlan.where.not(latitude: nil, longitude: nil)
    @seating_plan = SeatingPlan.find(params[:id])
    @super_tables = SuperTable.new(seating_plan: @seating_plan)

    @marker = [
      {
        lat: @seating_plan.latitude,
        lng: @seating_plan.longitude
      }
    ]
    respond_to do |format|
      format.html
      format.csv { send_data @seating_plan.to_csv }
      format.xls
    end
  end


  def update
    @seating_plan = SeatingPlan.find(params[:id])
    if @seating_plan.update(seating_plan_params)
      flash[:notice] = 'Successfully updated your wedding details'
      redirect_to seating_plan_path(@seating_plan)
    else
      render 'seating_plan/show'
    end
  end

  def export
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "My_Seating_Plan", footer: { right: '[page] of [topage]' },
               orientation: 'Landscape',
               layout: false,
               margin:  {   top:               5,                     # default 7 (mm)
                            bottom:            5,
                            left:              5,
                            right:             5 }
      end
    end
  end

  def deco
    @super_tables_pdf = SuperTable.new(seating_plan: @seating_plan)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "My_Decoration", footer: { right: '[page] of [topage]' },
               orientation: 'Landscape',
               layout: false,
               margin:  {   top:               10,                     # default 7 (mm)
                            bottom:            5,
                            left:              5,
                            right:             5 }
      end
    end
  end

  private

  def seating_plan_params
    params.require(:seating_plan).permit(:nb_participants, :nb_max_participants, :name, :date, :address)
  end

end

app/views/seating_plans/deco.pdf.erb
<!DOCTYPE html>
<html>
  <head>
  <title>My Decoration</title>
  <meta charset='utf-8' />
      <%= wicked_pdf_stylesheet_link_tag "application" -%>
    <style>
      #pdf-menu {
        font-size: 18px;
        padding-bottom: 50px;
      }
      .pdf-padding {
        padding: 45px 0px;
      }

      .page-break-after { page-break-inside: avoid; }

      #card-pdf {
        height: 575px;
      }
      #card-info-pdf {
        height: 515px;
      }

      #test {
          background-image: url('image_2.png');
      }

    </style>
  </head>



  <body>

  <div class='container'>
    <div class="row">
      <% @seating_plan.participants.each do |participant| %>
        <div class="col-xs-4 page-break-after">
          <div class="card-org">
            <div class="card-name other_cadre">
              <div class="card-info">
                <div class="card-title text-center">
                  <%= participant.decoration_name %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-xs-8 col-xs-offset-2 page-break-after">
      <div class="card other_cadre">
        <div class="card-info">
          <div class="card-title text-center pdf-padding">MENU</div>
          <div class="card-content-menu text-center" id="pdf-menu">
            <ul class="list-unstyled menu">
              <li>Crisp Romaine, Poached Pears, Toasted Hazelnuts, Dried Cranberries, Crumbled Blue Cheese Dressing</li>
              <li><%= wicked_pdf_image_tag("separateur2.png", id:"separe" )%></li>
              <li>Grilled Pork Tenderloin, Caramelized Peppers, Roasted Brussells Sprouts, Farmhouse Mashed Potatoes</li>
              <li><%= wicked_pdf_image_tag("separateur2.png", id:"separe" )%></li>
              <li>Veronica’s Sweet Cakes</li>
              <li><%= wicked_pdf_image_tag("separateur2.png", id:"separe" )%></li>
              <li>Coffee and Assorted Teas</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <% @seating_plan.tables.order(:id).each_with_index do |table, index| %>
      <% unless @super_tables_pdf.table_empty(index) %>
      <div class="col-xs-6 page-break-after" >
        <div class="card other_cadre" id="card-pdf">
          <div class="card-info" id="card-info-pdf">
            <div class="card-title text-center">
                <h2><%= table.name %> </h2>
                <div class="card-content text-center">
                    <% @super_tables[index].each do |seat| %>
                      <ul class="list-unstyled">
                        <% if seat[:participant_id].present? %>
                          <li><%= seat[:name] %></li>
                        <% end %>
                      </ul>
                    <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>




  </div>




  </body>





</html>

app/views/seating_plans/export.pdf.erb
<!doctype<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <title>My Seating PLan</title>
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>

    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
    <style>
      .flexrow {
        display: -webkit-box;
        display: -webkit-flex;
        display: flex;
      }

      .flexrow > div {
        -webkit-box-flex: 1;
        -webkit-flex: 1;
        flex: 1;
        margin-right: 10%;
        border: 1px solid rgb(160,160,160);
      }

      .flexrow > div:last-child {
        margin-right: 0;
      }


      .flexcenter {
        display: -webkit-box;
        display: -webkit-flex;
        display: flex;
      }

      .flexcenter > div {
        -webkit-box-flex: 1;
        -webkit-flex: 1;
        flex: 1;
        box-align: center;
        box-pack: center;
      }

      #background-white {
        background-color: white;
      }

      .page-break-after { page-break-inside: avoid; }

      .test {
        width: 20px;
        height: 20px;
      }

    </style>
  </head>


 <body>

    <div class="container">
        <div class="table-container">
          <div class="row">

            <div class="col-xs-12">
              <div class="wedding-title-pdf">
                <h3><strong> Wedding of <%= current_user.bride_first_name %> and <%= current_user.groom_first_name %></strong></h3>
                <p>Seating plan done with HappySeat.fr <%= wicked_pdf_image_tag "chaise.png" %></p>
              </div>
            </div>
          </div>

          <div class="render-table-pdf">
              <%= render "tables/pdf_table" %>
          </div>

        </div>
    </div>
  </body>
</html>

app/views/seating_plans/show.html.erb
<div class="wrapper">


<div class="toolbar1 seating-plan-toolbar">
  <div class="card-info-toolbar">
      <div class="weds-ref">Wedding of:</div>
      <div class="card-title-weds">
        <em><%= @seating_plan.participants.find_by(status: "b").first_name if @seating_plan.participants.find_by(status: "b").present? %></em>
        and
        <em><%= @seating_plan.participants.find_by(status: "g").first_name if @seating_plan.participants.find_by(status: "g").present? %></em>
      </div>

      <div class="row weds-dispo">

        <%=image_tag("Flat 03 V2.png", :size=> "150x150", class: "bobby") %>
        <%=image_tag("marieF v2.png", :size=> "150x150", class: "mariee")%>

      </div>
      <div class="separteur3 text-centered"><%=image_tag("a315ba465d59cdd28b479191aef7c070.png", :width=> "280")%></div>
      <div class="weds-ref">My wedding details :</div>
      <div class= weds-address>
        <%= simple_form_for @seating_plan do |f| %>
          <%= f.error_notification %>
          <%= f.input :address, required: true, placeholder: "Address", label: false, autofocus: true %>
          <%= f.input :wedding_date, required: true, label: false %>
          <%= f.button :submit, class: "btn-success details-btn" %>
         <% end %>

      </div seating-plan-map>
      <div id="map" class="map hidden-xs" style="width: 100%" data-markers="<%= @marker.to_json %>">
      </div>
    </div>
  </div>


<div class="seating-plan-show">
  <div class="congrats">
    <h2>Congratulations</h2>
  </div>

  <div>
    <div class="container">

      <div class="row card-description2">
        <div class="col-xs-12 col-sm-7 ">
          <div class="card-print">
          <div class="card-info">

            <div class="card-content"><%= image_tag("chaise.png")%>
            <div class="print">
              <div class="card-title">Print your Seating plan in PDF</div>
              <%= link_to 'I DO', seating_plan_export_path(@seating_plan, :format => :pdf), class: "btn-congrats-print", target: "blank" %>
            </div>
            </div>
          </div>
          </div>
        </div>

        <div class="col-xs-12 col-sm-3">
          <div class="card-print">
          <div class="card-info-print">


            <div class="card-title-print">Export my guests list to excel</div>


              <%= link_to "I DO", seating_plan_path(format: "xls"), class: "btn-congrats-print large" %></div>


          </div>
          </div>
        </div>
      </div>

      <div class= "row card-description1"">
        <div class="card-print">
            <div class="card-title-cadre">Preview of your table decoration</div>
        </div>

        <div class="row card-description1">
          <div class= "row deco-info">
            <div class="col-xs-12 col-sm-4 w-33" >Seating plan card</div>
            <div class="col-xs-12 col-sm-4 w-33">Menu</div>
            <div class="col-xs-12 col-sm-4 w-33">Table place card</div>
          </div>


          <div class="col-xs-12 col-sm-4 ">
            <div class="card">
            <div class="card-info">
              <div class="card-title">
                <% [@seating_plan.tables.order(:id).first].each_with_index do |table, index| %>
                  <% unless @super_tables.table_empty(index) %>
                    <h2><%= table.name %> </h2>
                    <div class="card-content">
                        <% @super_tables.list[index].each do |seat| %>
                          <ul class="list-unstyled">
                            <% if seat[:participant_id].present? %>
                              <li><%= seat[:name] %></li>
                            <% end %>
                          </ul>
                        <% end %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
            </div>
          </div>

          <div class="col-xs-12 col-sm-4 ">
            <div class="card">
            <div class="card-info">
              <div class="card-title">MENU</div>
              <div class="card-content-menu">
                <ul class="list-unstyled menu">
                  <li>Crisp Romaine, Poached Pears, Toasted Hazelnuts, Dried Cranberries, Crumbled Blue Cheese Dressing</li>
                  <li><%= image_tag("separateur2.png", id:"separe" )%></li>
                  <li>Grilled Pork Tenderloin, Caramelized Peppers, Roasted Brussells Sprouts, Farmhouse Mashed Potatoes</li>
                  <li><%= image_tag("separateur2.png", id:"separe" )%></li>
                  <li>Veronica’s Sweet Cakes</li>
                  <li><%= image_tag("separateur2.png", id:"separe" )%></li>
                  <li>Coffee and Assorted Teas</li>
                </ul>
              </div>
            </div>
            </div>
          </div>

          <div class="col-xs-12 col-sm-4 ">
            <div class= card-org>
              <div class="card-name">
                <div class="card-info">
                  <div class="card-title"><%= @seating_plan.participants.first.decoration_name %></div>
                </div>
              </div>
              <%= link_to "I DO", seating_plan_deco_path(@seating_plan, :format => :pdf), class: "btn-congrats-print large", target: "blank" %></div>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>

</div>

app/views/seating_plans/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="wedding_participant_list">
    <Table>
      <Row>

        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Age range</Data></Cell>
        <Cell><Data ss:Type="String">Family type</Data></Cell>
        <Cell><Data ss:Type="String">Seat</Data></Cell>

      </Row>
    <% @seating_plan.participants.each do |participant| %>
      <Row>
        <Cell><Data ss:Type="String"><%= participant.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participant.age_range %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participant.family_type %></Data></Cell>
        <Cell><Data ss:Type="String"><%= participant.seat %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>