config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :seating_plans, only: [:create, :show, :update ] do
    resources :tables, only: [:index, :update]
    resources :participants, only: [:create] do
      patch 'swap'
      put 'swap'
    end
    resources :relationships, only: [:create]
    get 'export'
    get 'deco'
 end

  resources :participants, only: [:update, :destroy], shallow: true

  get 'tables/find_for_modal', as: "find_for_modal"



end

app/views/shared/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
<link rel="manifest" href="/favicon/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_flashes.html.erb
<% if notice %>
    <% if current_page? root_path %>
      <div class="alert alert-dismissible alert-info" role="alert">
    <% else %>
      <div class="alert alert-dismissible alert-test" role="alert">
    <% end %>

      <div class="alert-child">
        <%= notice %>
        <button type="button" class="close alert-child" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
    </div>

<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if current_page? root_path %>
  <div class="navbar-wagon navbar-fixed-top" >
<% else %>
  <div class="navbar-wagon navbar-sticky-top navbar-wagon-white">
<% end %>
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "chaise.png", id: "logo" %>

  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <% if @seating_plan.present? && @seating_plan.id?%>
        <div class="search">
          <%= render 'shared/search', query: params[:query] %>
        </div>
      <% else  %>
          <div class="test"></div>
      <% end %>


      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "", class: "fa fa-bars dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <% current_user.seating_plans.each_with_index do |seating_plan, index| %>
                <%= link_to (seating_plan_tables_path(seating_plan)) do %>
                  <i class="fa fa-cog"></i>  <%= "My seating plan n° #{index}" %>
                <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
       <%= link_to t(".sign_in", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "#" do %>
            <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li>
            <% current_user.seating_plans.each_with_index do |seating_plan, index| %>
              <%= link_to (seating_plan_tables_path(seating_plan)) do %>
                <i class="fa fa-cog"></i>  <%= "My seating plan N° #{index}" %>
              <% end %>
            <% end %>
          </li>
         <% end %>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= simple_form_for :search, url: find_for_modal_path, method: :get, html: { class: 'form-inline', id: 'search-form' }, remote: true do |f| %>
  <%= f.input :seating_plan_id, input_html: {value: @seating_plan.id}, as: :hidden %>
  <%= f.input :participant_id, collection: @seating_plan.participants.order(:last_name).map{|p| [p.name, p.id]}, input_html: {class: 'select2'}, label: false %>
  <%= f.button :submit, id: "submit-form", data: {target: "#exampleModalParticipant", toggle: "modal"}, class: 'btn btn-happy-grey btn-small'%>

<% end %>