config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :seating_plans, only: [:create, :show, :update ] do
    resources :tables, only: [:index, :update]
    resources :participants, only: [:create] do
      patch 'swap'
      put 'swap'
    end
    resources :relationships, only: [:create]
    get 'export'
    get 'deco'
 end

  resources :participants, only: [:update, :destroy], shallow: true

  get 'tables/find_for_modal', as: "find_for_modal"



end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :init, only: [:index, :update]

  def index
    @relationship = Relationship.new
    @participant = Participant.new
    @participants = Participant.all
  end

  def find_for_modal
    @participant = Participant.find(search_params[:participant_id])
    @relationship = Relationship.new
    respond_to do |format|
      format.html { redirect_to seating_plan_tables_path(search_params[:seating_plan_id]) }
      format.js
    end
  end


  def update
    @table = Table.find(params[:id])
    if @table.update(tables_params)
      flash[:notice] = 'Successfully updated your table name'
      redirect_to seating_plan_tables_path(@seating_plan)
    else
      render 'tables/index'
    end
  end

private

  def search_params
    params.require(:search).permit(
      :participant_id,
      :seating_plan_id
      )
  end

  def tables_params
    params.require(:table).permit(:name)
  end

end

app/views/tables/_avatar.html.erb
<div class="avatar-participant <%= avatar_colored(seat[:seat_id]) %>" data-path="<%= seating_plan_participant_swap_url(@seating_plan, seat[:participant_id])%>" data-pid="<%= seat[:participant_id] %>">
  <div class="avatar-middle">
    <p><%= seat[:initials] %></p>
    <div class= "<%= avatar_family(seat[:seat_id]) %>" ></div>
  </div>
  <div class="middle">
    <div class="text-middle"><%= seat[:name]%></div>
  </div>
</div>

app/views/tables/_modalParticipant.html.erb
<div class="modal fade" id="exampleModalParticipant" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="participant-modal-header" style="background-image: linear-gradient(-225deg, rgba(70,70,70,0.2) 0%, rgba(55,55,55,0.1) 20%), url('<%= image_path "modal-pic.png" %>');">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-text">
          <div class="modal-left">
            <div class="modal-body" id="modalParticipant"></div>
          </div>

          <div class="modal-right">
            <div class="modal-body2" id="modalParticipant2"></div>
          </div>
        </div>

        <div class="modal-bottom">
          <div class="modal-body3" id="modalParticipant3"></div>
        </div>
    </div>
  </div>
</div>

app/views/tables/_modalRelationship.html.erb
<div class="modal fade" id="exampleModalRelationship" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            <div class="modal-header header-size">
              <h5 class="modal-title" id="exampleModalLongTitle">Define a conflictual relationship</h5>
              <p>Select the 2 persons that can not be seated at the same table</p>
            </div>

            <div class="modal-body">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">

                    <div class="form-hate">
                    <%= simple_form_for [@seating_plan, @relationship] do |t| %>
                    <%= t.input :link, input_html: {value: "hate"}, as: :hidden %>
                    <div id="first_guest">

                        <%= t.input :first_guest_id, collection: @seating_plan.participants.order(:last_name), required: true, prompt: "Select 1st Guest", label: false  %>
                    </div>

                    <div class="braked_heart text-center">
                        <%= image_tag "braked-heart.png" %>
                    </div>

                    <div id="second_guest">

                        <%= t.input :second_guest_id, collection: @seating_plan.participants.order(:last_name), required: true, prompt: "Select 2nd Guest", label: false  %>
                    </div>
                    <%= t.button :submit, class: "btn-success btn-max"%>
                    <% end %>
                  </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/tables/_modal_body.html.erb
<div class="toolbar-form">
  <h5>Participants details</h5>
  <div class="modal-details">
    <p><%= participant.table_nb.present? ? participant.table_nb : "No Table" %> - Seat N° <%= participant.seat.present? ? participant.seat : "No seat for now"  %></p>
  </div>
  <div class="toolbar-form-one-participant">
  <%= simple_form_for participant do |f| %>
    <%= f.error_notification %>
    <%= f.input :first_name, required: true, placeholder: "First Name", label: false %>
    <%= f.input :last_name, required: true, placeholder: "Last Name", label: false %>
    <div class="nested-prompt">
      <%= f.input :age_range, collection: Participant.age_ranges.keys, prompt: "Age", required: true, label: false, class: "prompt-size nested-prompt-age", label_method: lambda { |age| "#{age.capitalize}" } %>
      <%= f.input :family_type, collection: Participant.family_types.keys, prompt: "Family Link", required: true, label: false, label_method: lambda { |family| "#{family.capitalize}" } %>
    </div>
    <%= f.button :submit, class: "btn-success" %>
   <% end %>
  </div>
</div>

app/views/tables/_modal_body2.html.erb
    <h5>Relationship(s) associated</h5>
    <div class="modal-details">
      <% if Relationship.where(first_guest: participant).empty? %>
        <p class="text-center" >No Relationship recorded</p>
      <% else %>
        <ul>
        <% Relationship.where(first_guest: participant).each do |relation| %>
        <li>
          <p>Relation : <%= relation.link %> with <%= relation.second_guest.name %></p>
        </li>
        <% end %>
        </ul>
      <% end %>
    </div>

app/views/tables/_modal_body3.html.erb
 <div class="modal-toolbar-form-couple">
  <h5>Add Conflictual Relationship <%= image_tag "braked-heart.png" %></h5>
  <p>Define a conflictual relationship with another guest</p>

    <%= simple_form_for [participant.seating_plan, relationship] do |t| %>
    <%= t.input :link, input_html: {value: "hate"}, as: :hidden %>
    <div id="first_guest">
        <%= t.input :first_guest_id, input_html: {value: participant.id}, as: :hidden   %>
    </div>
    <div id="second_guest">
        <%= t.input :second_guest_id, collection: participant.seating_plan.participants.order(:last_name), required: true, prompt: "Select a guest", label: false  %>
    </div>
    <%= t.button :submit, class: "btn-success btn-max"%>
    <% end %>

</div>

app/views/tables/_pdfTables.html.erb
 <div class="row">
  <% @tables.each_with_index do |table, index| %>
    <div class="col-xs-4">
      <div class="table-section" >

        <div class="table-card-name text-left">
          <div class="name"><h3><%= table.name %></h3></div>
          <div class="pencil">

            <%= link_to seating_plan_table_path(@seating_plan, table), method: :patch do %>
            <a role="button" data-toggle="collapse" href='#collapseExample-<%= "#{index}" %>' aria-expanded="false" aria-controls="collapseExample">
            <i class="fas fa-pencil-alt"></i></a>
            <div class="collapse" id='collapseExample-<%= "#{index}" %>'>
              <div class="table-name-form">
                <%= simple_form_for [@seating_plan, table] do |f| %>
                <%= f.error_notification %>
                <%= f.input :name, required: true, placeholder: "Table name", label: false %>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
        </div>


        <div class="table-card table-margin pdf-table-frame">
          <div class="avatar-frame flexrow" id='table-top-<%= "#{index}" %>'>

              <% @super_tables[index][0...(@super_tables[index].size / 2)].each do |seat| %>
                <div class="avatar text-center padding-top-12" id="avatar-<%= seat[:seat_id] %>"><%= seat[:seat_id] %></div>
              <% end %>
          </div>

          <div class="table-frame frame-pdf">
            <ul class="list-unstyled">
              <div class="row">
                <% @super_tables[index].each do |seat| %>
                  <div class="col-xs-6">
                    <li class="pdf-name"><%= seat[:seat_id] %> - <%= @seating_plan.participants.find_by(seat: seat[:seat_id]).name if @seating_plan.participants.find_by(seat: seat[:seat_id]).present? %></li>
                  </div>
                <% end %>
              </div>
            </ul>
          <!--   <div class="table-frame-nappe">
          </div> -->
          </div>

          <div class="avatar-frame flexrow" id='table-bottom-<%= "#{index}" %>'>
              <% @super_tables[index][(@super_tables[index].size / 2)..-1].each do |seat| %>
                <div class="avatar text-center padding-top-12" id="avatar-<%= seat[:seat_id] %>"><%= seat[:seat_id] %></div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tables/_pdf_table.erb
 <div class="row">
  <% @tables.each_with_index do |table, index| %>
    <div class="col-xs-4 page-break-after">
      <div class="table-section">
      <div class="name"><h3 class="padding-left-10"><strong><%= table.name %></strong></h3></div>
        <div class="table-card no-padding-and-margin table-margin pdf-table-frame" id="background-white">
          <div class="avatar-frame flexrow" id='table-top-<%= "#{index}" %>'>
            <% @super_tables[index][0...(@super_tables[index].size / 2)].each do |seat| %>
              <div class="avatar text-center padding-top-12" id="avatar-<%= seat[:seat_id] %>"><%= seat[:seat_id] %></div>
            <% end %>
          </div>

          <div class="table-frame frame-pdf padding-top-9" id="height-frame">
            <ul class="list-unstyled">
              <div class="row">
                <% @super_tables[index].each do |seat| %>
                  <div class="col-xs-6">
                    <li class="pdf-name"><%= seat[:seat_id] %> - <%= @seating_plan.participants.find_by(seat: seat[:seat_id]).name if @seating_plan.participants.find_by(seat: seat[:seat_id]).present? %></li>
                  </div>
                <% end %>
              </div>
            </ul>
          </div>
          <div class="avatar-frame flexrow" id='table-bottom-<%= "#{index}" %>'>
              <% @super_tables[index][(@super_tables[index].size / 2)..-1].each do |seat| %>
                <div class="avatar text-center padding-top-12" id="avatar-<%= seat[:seat_id] %>"><%= seat[:seat_id] %></div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tables/_tablesDisplay.html.erb
<div class="wrapper-tables">
    <div class="container-fluid">

      <div class="row">
        <div class="col-xs-12">
          <div class="table-section">
            <div class="table-drop-zone-title">
              <h3>Guests Drop Zone</h3>
              <h6> Guests : <%= @seating_plan.participants.size %> / <%= @seating_plan.nb_participants %></h6>
            </div>

            <div class="table-drop-zone" id="drop-zone">
              <% @seating_plan.participants.where(seat: nil).each do |participant| %>
                <%= render 'avatar', seat: { participant_id: participant.id, seat_id: participant.seat, initials: participant.initial } %>
              <% end %>
             </div>
          </div>
        </div>
      </div>

      <div class="row">
        <% @tables.each_with_index do |table, index| %>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="table-section" >

              <div class="table-card-name text-left">
                <div class="name"><h3><%= table.name %></h3></div>
                <div class="pencil">

                  <%= link_to seating_plan_table_path(@seating_plan, table), method: :patch do %>
                  <a role="button" data-toggle="collapse" href='#collapseExample-<%= "#{index}" %>' aria-expanded="false" aria-controls="collapseExample">
                  <i class="fas fa-pencil-alt"></i></a>
                  <div class="collapse" id='collapseExample-<%= "#{index}" %>'>
                    <div class="table-name-form">
                      <%= simple_form_for [@seating_plan, table] do |f| %>
                      <%= f.error_notification %>
                      <%= f.input :name, required: true, label: false %>
                      <% end %>
                    </div>
                  </div>
                  <% end %>
                </div>
              </div>


              <div class="table-card">
                <div class="avatar-frame" id='table-top-<%= "#{index}" %>'>

                    <% @super_tables[index][0...(@super_tables[index].size / 2)].each do |seat| %>
                        <div class="avatar" id="avatar-<%= seat[:seat_id] %>">
                          <%= (render 'tables/avatar', seat: seat) if seat[:participant_id].present? %>
                        </div>
                    <% end %>
                </div>

                <div class="table-frame">
                  <div class="table-frame-nappe" style="background-image: url('<%= image_path "image_2.png" %>');"></div>
                </div>

                <div class="avatar-frame" id='table-bottom-<%= "#{index}" %>'>
                    <% @super_tables[index][(@super_tables[index].size / 2)..-1].each do |seat| %>
                        <div class="avatar" id="avatar-<%= seat[:seat_id] %>">
                          <%= (render 'tables/avatar', seat: seat) if seat[:participant_id].present? %>
                        </div>
                    <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="triangle triangle-2" id="chevron"></div>
  </div>

app/views/tables/_toolbar_guestsList.html.erb
<div class="toolbar-guests-container">
  <div class="toolbar-guests">
    <div class="toolbar-close text-right">
      <span>&times;</span>
    </div>

    <div class="toolbar-name">
       <h5>Your guests list</h5>
    </div>

    <div class="toolbar-list">
      <ul class="list-unstyled">
        <div class='display-left'>
          <div class="avatar-small avatar_pink"></div>
          <h6><em>Bride Family</em></h6>
        </div>
        <% @seating_plan.participants.where(family_type: 'bride').each do |p|%>
          <li> <h6><%= p.initial %> - <%= p.name %></h6> </li>
        <% end %>
      </ul>

       <ul class="list-unstyled">
        <div class='display-left'>
          <div class="avatar-small avatar_blue"></div>
          <h6><em>Groom Family</em></h6>
        </div>
        <% @seating_plan.participants.where(family_type: 'groom').each do |p|%>
          <li> <h6><%= p.initial %> - <%= p.name %></h6> </li>
        <% end %>
      </ul>

       <ul class="list-unstyled">
        <div class='display-left'>
          <div class="avatar-small avatar_color"></div>
          <h6><em>Others</em></h6>
        </div>
        <li><h6><%= "No guests for now..." if @seating_plan.participants.where(family_type: 'others').empty? %></h6></li>
        <% @seating_plan.participants.where(family_type: 'others').each do |p|%>
          <li> <h6><%= p.initial %> - <%= p.name %></h6> </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tables/find_for_modal.js.erb
document.getElementById('modalParticipant').innerHTML = '<%= j render "tables/modal_body", participant: @participant %>';
document.getElementById('modalParticipant2').innerHTML = '<%= j render "tables/modal_body2", participant: @participant %>';
document.getElementById('modalParticipant3').innerHTML = '<%= j render "tables/modal_body3", participant: @participant, relationship: @relationship %>';

app/views/tables/index.html.erb
<div class="wrapper">
  <!-- Toolbar -->

  <div class="toolbar">
    <div class="toolbar-legend">
      <h5 class="text-center" >Legend</h5>
      <div class="toolbar-legend-colors-details">
        <div class="toolbar-legend-colors">
          <div class="display-center"><div class="avatar-small avatar_age avatar_children"></div><h6>Children</h6></div>
          <div class="display-center"><div class="avatar-small avatar_age avatar_teenagers"></div><h6>Teenagers</h6></div>
          <div class="display-center"><div class="avatar-small avatar_age avatar_adults"></div><h6>Adults</h6></div>
          <div class="display-center"><div class="avatar-small avatar_age avatar_elderly"></div><h6>Elderly</h6></div>
        </div>
        <div class="toolbar-legend-colors">
          <div class="display-center"><div class="avatar-small avatar_pink"></div><h6>Bride Family</h6></div>
          <div class="display-center"><div class="avatar-small avatar_blue"></div><h6>Groom Family</h6></div>
          <div class="display-center"><div class="avatar-small avatar_color"></div><h6>Others guests</h6></div>
        </div>
      </div>
      <button type="button" class="btn btn-happy-grey btn-small btn-normal" data-toggle="modal" data-target="#exampleModalRelationship">
        Add Conflictual Relationship
      </button>
       <%= link_to "Finalize your Seating Plan", seating_plan_path(@seating_plan), class: "btn btn-happy-grey btn-small btn-normal" %>
    </div>

    <div class="toolbar-name text-center">
      <h5>Add a Guest</h5>
      <%=  link_to "#", class: "btn btn-happy-grey active-couple"  do %>
        Or a couple <i class="fas fa-venus-mars"></i>
      <% end %>

      <%=  link_to "#", class: "btn btn-happy-grey active-couple hidden-couple"  do %>
        Or a participant <i class="fas fa-venus"></i>
      <% end %>
    </div>

    <div class="toolbar-form">
      <div class="toolbar-form-one-participant" id="form-recuperate">
        <%= simple_form_for [@seating_plan, @participant] do |f| %>
        <%= f.error_notification %>
          <%= f.input :first_name, required: true, placeholder: "First Name", label: false %>
          <%= f.input :last_name, required: true, placeholder: "Last Name", label: false %>
        <div class="nested-prompt">
          <%= f.input :age_range,
                      collection: Participant.age_ranges.keys,
                      prompt: "Age",
                      required: true,
                      label: false,
                      label_method: lambda { |age| "#{age.capitalize}" },
                      class: "prompt-size nested-prompt-age" %>
          <%= f.input :family_type,
                      collection: Participant.family_types.keys,
                      prompt: "Family Link",
                      required: true,
                      label: false,
                      label_method: lambda { |family| "#{family.capitalize}" } %>
        </div>
          <%= f.button :submit, class: "btn-success" %>
        <% end %>
      </div>

      <div class="toolbar-form-couple hidden-couple">
        <%= simple_form_for [@seating_plan, @relationship] do |t| %>
        <%= t.error_notification %>
        <%= t.input :link, input_html: {value: "couple"}, as: :hidden %>

        <div id="first_guest">
          <%= t.simple_fields_for :first_guest, @first_guest do |x| %>
            <!-- Task: <%#= task.text_field :name %> -->
            <div class="nested-fields">
              <h6>First Guest</h6>
              <%= x.input :first_name, required: true, placeholder: "First Name", label: false  %>
              <%= x.input :last_name, required: true, placeholder: "Last Name", label: false  %>
              <div class="nested-prompt">
                <%= x.input :age_range, collection: Participant.age_ranges.keys, prompt: "Age", required: true, label: false, class: "prompt-size nested-prompt-age", label_method: lambda { |age| "#{age.capitalize}" } %>
                <%= x.input :family_type, collection: Participant.family_types.keys, prompt: "Family Link", required: true , label: false,label_method: lambda { |family| "#{family.capitalize}" } %>
              </div>
            </div>
          <% end %>
        </div>
        <hr>
        <div id="second_guest">
          <%= t.simple_fields_for :second_guest, @second_guest do |y| %>
            <div class="nested-fields">
              <h6>Second Guest</h6>
              <%= y.input :first_name, required: true, placeholder: "First Name" , label: false %>
              <%= y.input :last_name, required: true, placeholder: "Last Name", label: false  %>
              <div class="nested-prompt">
                <%= y.input :age_range, collection: Participant.age_ranges.keys, prompt: "Age", required: true, label: false, class: "prompt-size nested-prompt-age", label_method: lambda { |age| "#{age.capitalize}" } %>
                <%= y.input :family_type, collection: Participant.family_types.keys, prompt: "Family Link", required: true, label: false,label_method: lambda { |family| "#{family.capitalize}" }  %>
              </div>
            </div>
          <% end %>
        </div>

        <%= t.button :submit, class: "btn-success"%>
        <% end %>
      </div>
    </div>


    <!-- <div class="toolbar-buttons"> -->
      <!-- Button trigger modal -->
      <!-- <button type="button" class="btn btn-happy-grey btn-size" data-toggle="modal" data-target="#exampleModalRelationship">
        Add Conflictual Relationship
      </button> -->
      <%#= link_to "Finalize your Seating Plan", seating_plan_path(@seating_plan), class: "btn btn-happy-grey btn-size" %>
<!--     </div> -->

  </div>


  <!-- Modal -->
  <%= render "tables/modalRelationship" %>
  <%= render "tables/modalParticipant" %>
  <%= render "tables/tablesDisplay" %>
  <%= render "tables/toolbar_guestsList" %>

</div>
<!-- Footer -->